### ISSUE TITLE
Start integrating OAuth2: 15h

### ISSUE THREAD

**Issue by Ratchet34702** [Wectro20/intellistart-java-2022-propositum#28]
1. Learn base aspects of implementing OAuth2
2. Make necessary settings and preparations

**Comment by VovaMitsura** [comment]
20.10 self-implementation of usign Jwt token and saving users in Mysql DB
`https://github.com/VovaMitsura/JwtWithMySql`

**Comment by VovaMitsura** [comment]
21.10 simple autherization with auth2 
`https://github.com/VovaMitsura/oauth2_demo`
