### ISSUE TITLE
Implement endpoint to update Interviewer Time Slot: 20h

### ISSUE THREAD

**Issue by Olena25** [Wectro20/intellistart-java-2022-propositum#6]
We need to have endpoint to be able to update Interviewer Time Slot.

Specification:

```

POST /interviewers/<interviewerId>/slots/<slotId>

{
    "weekNum": 12,
    "dayOfWeek": "Fri",
    "from": "10:00",
    "to": "17:00"
}
```

Response:

```
{
    "id": "<slotId>",
    "weekNum": 12,
    "dayOfWeek": "Fri",
    "from": "9:00",
    "to": "17:00"
}
```

Errors:

**interviewer_not_found**
**slot_not_found**
**slot_is_overlaping**: is existing slot is already there
**invalid_boundaries**: e.g. if "9:02" or the start is after the end or violates working time (8:00-22:00)
**invalid_day_of_week**: e.g. "sundday"
**cannot_edit_this_week**: if Interviewer trying to change current (or previous) week slot, however Coordinator is allowed to do this

**Comment by Sviat2001** [comment]
Add tests and cannot_edit_this_week error
